package pl.backend.weddinggallery.audit.model;

public enum EventType {
	ADMIN_BOOTSTRAPPED, USER_REGISTERED, USER_LOGGED_IN, USER_LOGIN_FAILED, USER_LOGIN_BLOCKED, USER_LOGGED_OUT, EVENT_CREATED, EVENT_UPDATED, EVENT_ARCHIVED, EVENT_DELETED, EVENT_MANAGER_ADDED, EVENT_MANAGER_REMOVED, EVENT_OWNERSHIP_TRANSFERRED, GALLERY_CREATED, GALLERY_UPDATED, GALLERY_ARCHIVED, GALLERY_DELETED, GALLERY_SETTINGS_UPDATED, GALLERY_ACCESS_TOKEN_ROTATED, GALLERY_ACCESS_CODE_CHANGED, MEDIA_STORED, MEDIA_PROCESSING_SUCCEEDED, MEDIA_PROCESSING_FAILED
}
