package pl.backend.weddinggallery.audit.model;

public enum EventType {
	USER_REGISTERED, USER_LOGGED_IN, USER_LOGIN_FAILED, USER_LOGIN_BLOCKED, USER_LOGGED_OUT, EVENT_CREATED,
	EVENT_UPDATED, EVENT_ARCHIVED, EVENT_DELETED, EVENT_MANAGER_ADDED, EVENT_MANAGER_REMOVED,
	EVENT_OWNERSHIP_TRANSFERRED
}
